# Generated by Django 4.2.11 on 2024-08-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_filmwork_options_alter_genre_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[
                    ("DIR", "Director"),
                    ("ACT", "Actor"),
                    ("PROD", "Producer"),
                    ("WRIT", "Writer"),
                    ("CINE", "Cinematographer"),
                    ("EDIT", "Editor"),
                    ("OTH", "Other"),
                ],
                default="OTH",
                max_length=20,
                verbose_name="role",
            ),
        ),
        migrations.AddIndex(
            model_name="filmwork",
            index=models.Index(fields=["created"], name="film_work_creation_date_idx"),
        ),
        migrations.AddIndex(
            model_name="genrefilmwork",
            index=models.Index(
                fields=["film_work"], name="genre_film_work_filmwork_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="genrefilmwork",
            index=models.Index(fields=["genre"], name="genre_film_work_genre_idx"),
        ),
        migrations.AddIndex(
            model_name="genrefilmwork",
            index=models.Index(
                fields=["film_work", "genre"], name="genre_film_work_fw_genre_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personfilmwork",
            index=models.Index(
                fields=["film_work", "person", "role"], name="film_work_person_role_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="genrefilmwork",
            constraint=models.UniqueConstraint(
                fields=("film_work", "genre"), name="unique_film_genre"
            ),
        ),
        migrations.AlterModelTable(
            name="personfilmwork",
            table='content"."person_film_work',
        ),
    ]
