# Generated by Django 4.2.11 on 2024-07-02 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_filmwork"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="rating",
            field=models.FloatField(
                blank=True,
                default=13,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="rating",
            ),
            preserve_default=False,
        ),
    ]
